name: Docker Image CI to Artifact Registry

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Give image a tag'
        required: true
        type: string

env:
  PROJECT_ID: ob-sax
  GCP_REGION: europe-north2
  REGISTRY_URL: europe-north2-docker.pkg.dev/ob-sax/ping-pong-cluster-docker
  IMAGE: ping-pong-api
  GKE_CLUSTER_NAME: ping-pong-cluster

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Google Auth
        id: auth
        uses: google-github-actions/auth@v2
        with:
          project_id: ${{ env.PROJECT_ID }}
          credentials_json: ${{ secrets.GCP_SA_KEY }}
      
      - name: Get GKE credentials
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: ${{ env.GKE_CLUSTER_NAME }}
          location: ${{ env.GCP_REGION }}
          project_id: ${{ env.PROJECT_ID }}

      - name: Set environment variables
        run: |
          echo "IMAGE_TAG=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Artifact Registry
        run: gcloud auth configure-docker ${{ env.GCP_REGION }}-docker.pkg.dev

      - name: Build Docker image to Artifact Registry
        run: |
          docker build \
          --tag "${{ env.REGISTRY_URL }}/${{ env.IMAGE }}:${{ env.IMAGE_TAG }}" \
          --tag "${{ env.REGISTRY_URL }}/${{ env.IMAGE }}:latest" \
          --cache-from "${{ env.REGISTRY_URL }}/${{ env.IMAGE }}:latest" .

      - name: Run security scan on image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ env.REGISTRY_URL }}/${{ env.IMAGE }}:${{ env.IMAGE_TAG }}'
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'
          exit-code: '1'
        continue-on-error: true

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'

      - name: Push Docker image
        run: |-
          docker push "${{ env.REGISTRY_URL }}/${{ env.IMAGE }}:${{ env.IMAGE_TAG }}"
          docker push "${{ env.REGISTRY_URL }}/${{ env.IMAGE }}:latest"

      - name: Run helm chart
        run:  |
          helm upgrade --install ${{ env.IMAGE }} ./helm/${{ env.IMAGE }} \
          --set image.tag=${{ env.IMAGE_TAG }} \
          --set image.repository="${{ env.REGISTRY_URL }}/${{ env.IMAGE }}" \
          --set image.tag="${{ env.IMAGE_TAG }}" \
          --set replicaCount=2 \
          --wait \
          --timeout=5m

      - name: Verify deployment
        run: |-
          kubectl rollout status deployment/${{ env.IMAGE }}
          kubectl get services -o wide