name: Docker Image CI to Artifact Registry

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

env:
  PROJECT_ID: ob-sax
  GCP_REGION: europe-north2
  AR_REPO_NAME: ping-pong-cluster-docker
  IMAGE_NAME: ping-pong-api
  GKE_CLUSTER_NAME: ping-pong-cluster

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Google Auth
        id: auth
        uses: google-github-actions/auth@v2
        with:
          project_id: ${{ env.PROJECT_ID }}
          credentials_json: ${{ secrets.GCP_SA_KEY }}
      
      - name: Get GKE credentials
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: ${{ env.GKE_CLUSTER_NAME }}
          location: ${{ env.GCP_REGION }}
          project_id: ${{ env.PROJECT_ID }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Artifact Registry
        run: gcloud auth configure-docker ${{ env.GCP_REGION }}-docker.pkg.dev

      - name: Build/Push Docker image to Artifact Registry
        run: |
          docker build -t europe-north2-docker.pkg.dev/ob-sax/ping-pong-cluster-docker/ping-pong-api:${GITHUB_SHA::7} .
          docker push europe-north2-docker.pkg.dev/ob-sax/ping-pong-cluster-docker/ping-pong-api:${GITHUB_SHA::7}

      - name: Run helm chart
        run:  |
          helm upgrade --install ping-pong-api-release ping-pong-api \
          --set image.tag=${GITHUB_SHA::7} \
          --wait

