name: Docker Image CI to Artifact Registry

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"

env:
  PROJECT_ID: ob-sax
  GCP_REGION: europe-north2
  AR_REPO_NAME: ping-pong-cluster-docker
  IMAGE_NAME: ping-pong-api

jobs:
  build_and_push:
    working-dir: docker
    runs-on: ubuntu-latest
    permissions:
      contents: read
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Google Auth
        id: auth
        uses: google-github-actions/auth@v2
        with:
          project_id: ${{ env.PROJECT_ID }}
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Artifact Registry
        run: gcloud auth configure-docker ${{ env.GCP_REGION }}-docker.pkg.dev

      - name: Build and push Docker image to Artifact Registry
        uses: docker/build-push-action@v5
        working-directory: ./docker
        with:
          file: Dockerfile
          platforms: linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ github.ref_name }}
